"""
Features Module - Voice Assistant Commands
This module contains all the feature functions for the voice assistant.

CHANGES MADE:
- Added portable file path handling for camera images and screenshots
- Removed hardcoded Google API key (moved to environment variable)
- Uses assets.get_output_path() for cross-platform compatibility
- All output files are saved relative to project root
"""

import spotipy
from spotipy.oauth2 import SpotifyOAuth
import cv2
# CHANGED: Use centralized assets module for portable file path handling
import assets
import os
import tkinter as tk
import webbrowser
import datetime
import urllib.parse
import psutil
import pyautogui
import pyjokes
import google.generativeai as genai
import requests
import wikipedia
from bs4 import BeautifulSoup
import functions as func
from game_hub import start_game_hub

reminders = []
# CHANGED: Load Google API key from environment variable
genai.configure(api_key=os.environ.get("GOOGLE_API_KEY", ""))

def ai(user_input):
    model = genai.GenerativeModel("gemini-1.5-flash")

    try:
            response = model.generate_content(user_input)
            func.speak(response.text)

    except Exception as e:
            func.speak("Sorry, there was an error processing your request.", str(e))

def get_weather(city, api_key):
    try:
        response = requests.get(
            f"https://api.openweathermap.org/data/2.5/weather?q={city}&units=imperial&APPID={api_key}")
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        func.speak("Sorry, I couldn't get the weather information.")
        print(f"An error occurred: {e}")
        return None

def show_weather_details(city, weather, temp, humidity, wind_speed):
    # Create a new window
    weather_window = tk.Tk()
    weather_window.title("Weather Information")

    # Set the background color
    weather_window.configure(bg='lightblue')

    # Format the weather details
    details = (
        f"Weather in {city}:\n"
        f"Condition: {weather}\n"
        f"Temperature: {temp}°F\n"
        f"Humidity: {humidity}%\n"
        f"Wind Speed: {wind_speed} mph"
    )

    # Create a label to show the weather details with colorful text
    weather_label = tk.Label(
        weather_window,
        text=details,
        padx=10,
        pady=10,
        bg='lightblue',
        font=('Arial', 14),
        fg='darkblue'
    )
    weather_label.pack(pady=20)

    # Make the window stay open until it is closed by the user
    weather_window.mainloop()


def showCommands():
    commands = (
        "Here are the commands you can use, Boss:\n"
        "1. 'Wikipedia' followed by a topic to search Wikipedia.\n"
        "2. 'Open YouTube' to open YouTube.\n"
        "3. 'Search YouTube for' followed by your query to search on YouTube.\n"
        "4. 'Open Google' to open Google.\n"
        "5. 'Search Google for' followed by your query to search on Google.\n"
        "6. 'Tell a story' to hear a story generated by AI.\n"
        "7. 'Continue the story' to continue the last story.\n"
        "8. 'The time' to know the current time.\n"
        "9. 'Open code' to open Visual Studio Code.\n"
        "10. 'Add reminder' to add a reminder.\n"
        "11. 'Show reminder' to display reminders.\n"
        "12. 'Tell me a joke' to hear a joke.\n"
        "13. 'Calculate' followed by an expression to calculate a result.\n"
        "14. 'Features' to know about my capabilities.\n"
        "15. 'Commands' to hear this list of commands again.\n"
        "16. 'Let's play' or 'Play a game' to open the Game Hub.\n"
        "17. 'Open notepad' to open Notepad.\n"
        "18. 'Locate' followed by a location to open a specific location.\n"
        "19. 'News headlines' to fetch the latest news headlines.\n"
        "20. 'Search Wikipedia for' followed by a topic to search Wikipedia.\n"
        "21. 'Take screenshot' or 'Screen shot' to take a screenshot.\n"
        "22. 'Open calendar' to open the calendar.\n"
        "23. 'Open camera' to access the camera.\n"
        "24. 'System status' to display system status.\n"
        "25. 'Weather' to know about weather of any city"
        "25. 'Exit' to exit and shut down the assistant.\n"
    )
    return commands

def wish():
    hour = int(datetime.datetime.now().hour)
    if 0 <= hour < 12:
        return "Good Morning, Boss!"
    elif 12 <= hour < 18:
        return "Good Afternoon, Boss!"
    else:
        return "Good Evening, Boss!"

# Command functions
def open_google():
    webbrowser.open("https://www.google.com")

def open_youtube():
    webbrowser.open("https://www.youtube.com")

def google_search(command):
    query = command.replace("search google for", "").strip()
    webbrowser.open(f"https://www.google.com/search?q={urllib.parse.quote(query)}")

def youtube_search(command):
    query = command.replace("search youtube for", "").strip()
    webbrowser.open(f"https://www.youtube.com/results?search_query={urllib.parse.quote(query)}")

def respond(query):
    response = {
        "well done": "Thank you! I'm glad you liked it.",
        "keep it up": "I appreciate your support.",
        "great job": "Thanks! I'm always here to help you."
    }
    return response.get(query, "Thank you!")

def open_file_explorer():
    path = os.path.expanduser("~")  # Opens the user's home directory
    webbrowser.open(f'file://{path}')

def notepad():
    os.system("notepad.exe")

def location(query):
    location_query = query.replace("locate", "").strip()
    webbrowser.open(f"https://www.google.com/maps/place/{urllib.parse.quote(location_query)}")

def jokes():
    return pyjokes.get_joke()

def time():
    return datetime.datetime.now().strftime("%H:%M:%S")

def calendar():
    webbrowser.open("https://calendar.google.com")


def open_camera():
    # CHANGED: Use centralized assets module for portable file saving
    if not cv2.VideoCapture(0).isOpened():
        # Quick check - camera might not be available on all systems
        print("[WARNING] Camera may not be available on this system")
    
    cap = cv2.VideoCapture(0)  # Open the default camera (ID = 0)

    # Check if the camera opened successfully
    if not cap.isOpened():
        func.update_text_area("Error: Could not open the camera.")
        func.speak("Error: Could not open the camera.")
        return

    img_counter = 0
    func.speak("Camera is now open. Press 'p' to take a picture or 'q' to quit.")

    while True:
        ret, frame = cap.read()
        if not ret:
            func.update_text_area("Failed to grab frame.")
            func.speak("Failed to grab frame.")
            break

        # Display the frame in a window
        cv2.imshow('Camera', frame)

        # Detect key presses
        key = cv2.waitKey(1) & 0xFF
        if key == ord('p'):  # Shortcut for taking a picture
            # CHANGED: Use centralized assets.get_output_path() for portable saving
            img_name = f"picture_{img_counter}.png"
            img_path = assets.get_output_path(img_name)
            cv2.imwrite(str(img_path), frame)
            func.update_text_area(f"{img_name} saved!")
            func.speak(f"Picture {img_counter} saved!")
            img_counter += 1
        elif key == ord('q'):  # Quit the camera
            func.speak("Closing camera.")
            break

    # Release the camera and close windows
    cap.release()
    cv2.destroyAllWindows()


def sys_status():
    battery = psutil.sensors_battery()
    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory()
    status = (
        f"Battery: {battery.percent}% {'(Charging)' if battery.power_plugged else ''}\n"
        f"CPU Usage: {cpu}%\n"
        f"RAM Usage: {memory.percent}%"
    )
    return status

def wiki(query):
    search_term = query.replace("search wikipedia for", "").strip()
    try:
        summary = wikipedia.summary(search_term, sentences=2)
        return summary
    except wikipedia.exceptions.DisambiguationError as e:
        return f"Your search term is ambiguous. Options are: {e.options}"
    except wikipedia.exceptions.PageError:
        return "I couldn't find any information on that topic."

def convert(expression):
    ex = expression.lower()
    ex = ex.replace("plus", "+")
    ex = ex.replace("minus", "-")
    ex = ex.replace("times", "*")
    ex = ex.replace("into", "*")
    ex = ex.replace("by", "/")
    ex = ex.replace("divide", "/")
    ex = ex.replace("power", "**")
    ex = ex.replace("equals", "=")
    ex = ex.replace("x", "*")
    return ex

def calculation(ex):
    try:
        ex = ex.replace("calculate", "").strip()
        x = convert(ex)
        # Safe evaluation
        allowed_chars = "0123456789+-*/(). "
        if all(char in allowed_chars for char in x):
            result = eval(x)
            return result
        else:
            return "Invalid characters in expression."
    except Exception as e:
        return f"Error: {e}"

def fetch_headlines():
    url = "https://news.google.com/rss"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'xml')
    headlines = soup.find_all('item', limit=5)
    headline_list = "Here are the latest headlines: " + ", ".join(item.title.text for item in headlines)
    return headline_list

def news():
    webbrowser.open("https://news.google.com")

def screenshot():
    # CHANGED: Use centralized assets.get_output_path() for portable file saving
    screenshot = pyautogui.screenshot()
    screenshot_file = "screenshot.png"
    screenshot_path = assets.get_output_path(screenshot_file)
    screenshot.save(str(screenshot_path))
    webbrowser.open(str(screenshot_path))

def add_reminder(query):
    reminder = query.replace("add reminder", "").strip()
    if reminder:
        reminders.append(reminder)
        return "Reminder added."
    else:
        return "No reminder found to add."

def show_reminder():
    if reminders:
        reminder_list = "\n".join(reminders)
        return f"Your reminders are:\n{reminder_list}"
    else:
        return "You have no reminders."

def play_game_hub():
    func.speak("Launching Game Hub...")  # This will print to the console for debugging
    start_game_hub()


def open_stackoverflow():
    os.system("start https://stackoverflow.com")
    func.speak("Opening StackOverflow...")

def open_vscode():
    os.system("code")  # Assuming 'code' is set in environment variables
    func.speak("Opening Visual Studio Code...")

def fun_response():
    func.speak("I am just an assistant, but thanks for asking!")

def show_features():
    features = (
        "I can do many things, including searching on Google, "
        "opening websites, playing music, telling stories, and much more."
    )
    func.speak(features)

